### ISSUE TITLE
Functions not working due invalid URL formatting

### ISSUE THREAD

**Issue by tobias-scheepers** [supabase-community/supabase-py#463] opened 2023-06-14 09:21 UTC
Hi all,

Calling functions using supabase-py for me allways results in the following response: 

`{'data': b'Function not found', 'error': None}`

I believe this is due to the improper URL format in the `FunctionClient`:
https://github.com/supabase-community/supabase-py/blob/5c752443277de0a4a8dfd7d0d113f0d177efc81f/supabase/client.py#LL74C64-L74C64

Overwriting the `functions_url` in the following format seems to work for me: `"{}/rest/v1/rpc".format(url)`

**Comment by anand2312** [comment] 2023-06-14 13:23
Duplicate of #418 

I'll fix this tonight, I gotta read up a bit on functions 😄

**Comment by anand2312** [comment] 2023-06-14 16:42
@tobias-scheepers You're right, the functions URL is wrong (#447) but it won't be `/rest/v1/rpc` - that's the PostgREST endpoint to access functions defined in the database by remote procedure call, while the functions client is for supabase functions. See [js client docs](https://supabase.com/docs/reference/javascript/functions-invoke)

**Closed** 2023-06-15 03:43 UTC
Labels: duplicate
