### ISSUE TITLE
BUG | default schema not being applied in CI

### ISSUE THREAD

**Issue by LumixximuL** [supabase-community/supabase-py#106] opened 2021-12-26 22:18 UTC
**Describe the bug**
I am attempting to query a table in DB and getting an error in GitHub Actions that I am not getting running locally.

Query being attempted:
```
supabase.table('meeting_types').select('*').execute()
```

I get the error:
```
requests.exceptions.MissingSchema: Invalid URL '***/rest/v1/meeting_types?select=%2A': No schema supplied. Perhaps you meant http://***/rest/v1/meeting_types?select=%2A
```

Screen shot of error stack trace:
<img width="986" alt="Screen Shot 2021-12-26 at 4 10 41 PM" src="https://user-images.githubusercontent.com/6784596/147421165-b3ab24a6-f740-41fb-b49c-df65a9cad820.png">

I'm doing lots of querying and inserting locally with no issues. First time trying to replicate in CI and am getting this error. I'm using v0.0.3 of the supabase package and like I said I've been successfully running this locally and have replicated that setup in CI.

Let me know of any additional context you may need 👍 thanks in advance!

**Comment by anand2312** [comment] 2022-04-22 12:27
Apologies for the late response; does the bug still exist? I'm around 90% sure it should be fixed in newer versions of the library, but I haven't tried reproducing this in a CI environment yet.

**Comment by LumixximuL** [comment] 2022-04-24 19:46
I'll update to the latest version of the library and give it another try and report back.

**Comment by anand2312** [comment] 2022-04-25 04:50
Thank you so much!

Just seeing the traceback, I can guess what caused it: in the past, `postgrest-py` only supported async requests, so here at supabase-py we monkey-patched it to use the `requests` library to provide sync support ([Source](https://github.com/supabase-community/supabase-py/blob/6b76a9a2b318891c5c850f200d5077c50706375e/supabase/lib/query_builder.py#L9))
I'm guessing some headers, like the one for default schema were missed in this patch

**Comment by anand2312** [comment] 2022-05-14 17:37
Closing due to a lack of activity. I believe this should be fixed in the newer versions but if the issue persists, feel free to reopen.

**Closed by anand2312** 2022-05-14 17:37 UTC
Labels: bug
