### ISSUE TITLE
Can't filter urls. The ".com" causes the filter to not work

### ISSUE THREAD

**Issue by ConnorVO** [supabase-community/supabase-py#181] opened 2022-04-04 03:01 UTC
**Describe the bug**
If you try to filter URLs, it always returns empty data

**To Reproduce**
1. Create table with URL column
2. Run `supabase.<tablename>.select("*").eq("url", url).execute()`

**Expected behavior**
It should properly return the rows.

**Additional context**
If you remove the ".com" it works perfectly.

**Comment by anand2312** [comment] 2022-04-04 06:30
Duplicate of #161 ; I'll try looking into this over this weekend 😄

**Closed** 2022-04-07 13:16 UTC
