### ISSUE TITLE
"Realtime Changes" doesn't work with 'on'

### ISSUE THREAD

**Issue by swapnanildutta** [supabase-community/supabase-py#38] opened 2021-07-29 07:01 UTC
# Bug report

## Describe the bug

The "Realtime Changes" snippet on the README doesn't work. It throws an error with "AttributeError: 'RequestBuilder' object has no attribute 'on'"

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to any editor.
2. Type the code
 ```py
  import os
  from supabase_py import create_client, Client
  
  url: str = os.environ.get("SUPABASE_URL")
  key: str = os.environ.get("SUPABASE_KEY")
  supabase: Client = create_client(url, key)
  subscription = supabase.table('countries').on('*',  lambda x: print(x)).subscribe()
 ```
3. Run from terminal using ```python3 <script name>.py```

## Expected behavior

The snippet was expected to make a realtime change in the database, but it doesn't work because of this error
```bash
Traceback (most recent call last):
  File "/home/swapnanil/supabase-python-testing/script.py", line 7, in <module>
    subscription = supabase.table('countries').on('*',  lambda x: print(x)).subscribe()
AttributeError: 'RequestBuilder' object has no attribute 'on'
```

## Screenshots

![image](https://user-images.githubusercontent.com/47251193/127445828-a0ee65b3-c1f3-428c-97c8-633d3cb8b1ce.png)

## System information

- OS: Ubuntu
- Version of supabase-py [0.0.2]
- Version of Python3 [3.8.10]

**Comment by bariqhibat** [comment] 2021-10-04 12:58
Hey @swapnanildutta, if I look into the code myself, it is foreseeable that the example would throw this error. 

Since the `supabase.table('countries')` would create a new class of SupabaseQueryBuilder, which is a child class of PostgrestClient from postgrest-py repo, and calls the method `from_` upon declaring a new instance of that class. But, by executing `from_` method from the PostgrestClient class, we'd expect to receive a class of RequestBuilder, which doesn't have a method of `on`. While this `on` method exist in the SupabaseQueryBuilder. The `on` method is available on SupabaseQueryBuilder though.

So, we might need to add a new method of `on` and modify the example.

**Comment by bariqhibat** [comment] 2021-10-04 14:14
Duplicate https://github.com/supabase-community/supabase-py/issues/20

**Comment by anand2312** [comment] 2022-05-14 17:26
Duplicate of #20

**Closed by anand2312** 2022-05-14 17:26 UTC
Labels: bug
