### ISSUE TITLE
auth.signin without password always gives status code 200

### ISSUE THREAD

**Issue by SSardorf** [supabase-community/supabase-py#80] opened 2021-11-01 23:07 UTC
**Describe the bug**
Given the following code:
```
@user_route.get("/signin/")
async def signin(email:str, password:Optional[str]=None):
    if password:
        user = supabase.auth.sign_in(email=email, password=password)
    else:
        user = supabase.auth.sign_in(email=email)
    return user
```
If the else statement gets triggered(Sign in without a password), it sends a magic link to the user which allows them to sign up (I like this feature). However, it then returns a status code of 200. In the given case, how would you tell apart sign-ups from sign-ins?  

**Expected behavior**
Some sort of distinction between sign-in and sign-up in the case of passwordless sign-in

**Additional context**
Do educate me if this is not how I should look at it - It's my first time working with Supabase

**Comment by SSardorf** [comment] 2021-11-01 23:13
I suppose one way of checking whether the user is logged in versus signed up, is to check whether the returned dictionary contains more than just status_code. But would be nice to get more information than just `{"status_code":200}`

**Comment by J0** [comment] 2022-10-10 06:39
Hey! 

This is actually intended behaviour -- you can distinguish between signed-up and sign-ed in by checking the audit log (SignUpEvent vs login Event) or by checking if the given user is confirmed(without autoconfirm a signed up user would not be confirmed at time of clicking on the link whereas a user who is signing in would be confirmed.

Going to close this for now but please let us know if you are still facing issues

**Closed by J0** 2022-10-10 06:39 UTC
Labels: enhancement
