### ISSUE TITLE
rpc() - value is not a valid list

### ISSUE THREAD

**Issue by louis030195** [supabase-community/supabase-py#405] opened 2023-04-02 14:25 UTC
**Describe the bug**

`rpc()` crashes (calling a db function) with following error:

> ./tests/test_claims.py::test_get_claims Failed: [undefined]postgrest.exceptions.APIError: {'provider': 'email', 'providers': ['email'], 'claims_admin': True}
> self = <postgrest._sync.request_builder.SyncFilterRequestBuilder object at 0x103d5a680>
> 
>     def execute(self) -> APIResponse:
>         """Execute the query.
>     
>         .. tip::
>             This is the last method called, after the query is built.
>     
>         Returns:
>             :class:`APIResponse`
>     
>         Raises:
>             :class:`APIError` If the API raised an error.
>         """
>         r = self.session.request(
>             self.http_method,
>             self.path,
>             json=self.json,
>             params=self.params,
>             headers=self.headers,
>         )
>         try:
>             if (
>                 200 <= r.status_code <= 299
>             ):  # Response.ok from JS (https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)
> >               return APIResponse.from_http_request_response(r)
> 
> env/lib/python3.10/site-packages/postgrest/_sync/request_builder.py:66: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> cls = <class 'postgrest.base_request_builder.APIResponse'>
> request_response = <Response [200 OK]>
> 
>     @classmethod
>     def from_http_request_response(
>         cls: Type[APIResponse], request_response: RequestResponse
>     ) -> APIResponse:
>         try:
>             data = request_response.json()
>         except JSONDecodeError as e:
>             return cls(data=[], count=0)
>         count = cls._get_count_from_http_request_response(request_response)
> >       return cls(data=data, count=count)
> 
> env/lib/python3.10/site-packages/postgrest/base_request_builder.py:162: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> >   ???
> E   pydantic.error_wrappers.ValidationError: 1 validation error for APIResponse
> E   data
> E     value is not a valid list (type=type_error.list)
> 
> pydantic/main.py:342: ValidationError
> 
> The above exception was the direct cause of the following exception:
> 
>     def test_get_claims():
>         client = get_client()
> >       claims = get_claims(client, USER_ID)
> 
> tests/test_claims.py:11: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> middlewares/claims.py:27: in get_claims
>     res = client.rpc("get_claims", {"uid": uid}).execute()

Using `get_claims` function from:

https://github.com/wantpinow/supabase-custom-claims/blob/patch-1/install.sql

Is it because the function returns a `jsonb` ?

**To Reproduce**

1. Install the function `get_claims` from this PR https://github.com/wantpinow/supabase-custom-claims/blob/patch-1/install.sql
2. Call it from latest version of supabase-py

**Expected behavior**

Returns the function output

**Desktop (please complete the following information):**
 - OS: MacOS 13.3
 - Version `supabase==1.0.2`

**Comment by modyabhi** [comment] 2023-04-16 06:07
same issue here 

`ValidationError                           Traceback (most recent call last)
File [~/opt/anaconda3/envs/py10/lib/python3.10/site-packages/postgrest/_sync/request_builder.py:66](https://file+.vscode-resource.vscode-cdn.net/Users/amody/Downloads/pyasx-master/pyasx/~/opt/anaconda3/envs/py10/lib/python3.10/site-packages/postgrest/_sync/request_builder.py:66), in SyncQueryRequestBuilder.execute(self)
     63 if (
     64     200 <= r.status_code <= 299
     65 ):  # Response.ok from JS (https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)
---> 66     return APIResponse.from_http_request_response(r)
     67 else:

File [~/opt/anaconda3/envs/py10/lib/python3.10/site-packages/postgrest/base_request_builder.py:162](https://file+.vscode-resource.vscode-cdn.net/Users/amody/Downloads/pyasx-master/pyasx/~/opt/anaconda3/envs/py10/lib/python3.10/site-packages/postgrest/base_request_builder.py:162), in APIResponse.from_http_request_response(cls, request_response)
    161 count = cls._get_count_from_http_request_response(request_response)
--> 162 return cls(data=data, count=count)

File [~/opt/anaconda3/envs/py10/lib/python3.10/site-packages/pydantic/main.py:342](https://file+.vscode-resource.vscode-cdn.net/Users/amody/Downloads/pyasx-master/pyasx/~/opt/anaconda3/envs/py10/lib/python3.10/site-packages/pydantic/main.py:342), in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for APIResponse
data
  value is not a valid list (type=type_error.list)

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[19], line 1
----> 1 res = supabase.rpc('insert_subscription',payload).execute()

File [~/opt/anaconda3/envs/py10/lib/python3.10/site-packages/postgrest/_sync/request_builder.py:70](https://file+.vscode-resource.vscode-cdn.net/Users/amody/Downloads/pyasx-master/pyasx/~/opt/anaconda3/envs/py10/lib/python3.10/site-packages/postgrest/_sync/request_builder.py:70), in SyncQueryRequestBuilder.execute(self)
     68         raise APIError(r.json())
     69 except ValidationError as e:
---> 70     raise APIError(r.json()) from e
     71 except JSONDecodeError as e:
     72     raise APIError(generate_default_error_message(r))

File [~/opt/anaconda3/envs/py10/lib/python3.10/site-packages/postgrest/exceptions.py:21](https://file+.vscode-resource.vscode-cdn.net/Users/amody/Downloads/pyasx-master/pyasx/~/opt/anaconda3/envs/py10/lib/python3.10/site-packages/postgrest/exceptions.py:21), in APIError.__init__(self, error)
     19 def __init__(self, error: Dict[str, str]) -> None:
     20     self._raw_error = error
---> 21     self.message = error.get("message")
     22     self.code = error.get("code")
     23     self.hint = error.get("hint")

AttributeError: 'str' object has no attribute 'get'`

**Comment by Abdul-Rehman-Liaqat** [comment] 2023-04-19 10:32
@louis030195 @modyabhi @e-gons 
I had the same issue. Was able to make it work with the Table return type in the function.  For example following function is working:
`
CREATE OR REPLACE FUNCTION get_ids(id text)
RETURNS TABLE (id text[])
AS $$
BEGIN
  RETURN QUERY (
    SELECT array_agg(id::text)
    FROM (
      SELECT id
      FROM table1 
      LIMIT 20
    ) subquery
  );
END;
$$ LANGUAGE plpgsql;
`

And I get the same error if I get any other return type i.e. json, text , array etc.

**Comment by Lionardo** [comment] 2023-04-20 12:49
I have the same issue when calling a function. the same code worked well in  javascript

```
async def test_func():
    result = supabase.rpc("get_headphones_products", {})
    return result

data = None

resp = await test_func()
data = resp```

the response is: <postgrest._sync.request_builder.SyncFilterRequestBuilder object at 0x10fe32ee0>

**Comment by Abdul-Rehman-Liaqat** [comment] 2023-04-20 19:19
Yes, the issue is with python handling of data returned from supabase rpc call.

**Comment by 0xDeadcell** [comment] 2023-05-06 01:40
> 
change result = supabase.rpc("get_headphones_products", {}) -> result = await supabase.rpc("get_headphones_products", {}).execute()

**Comment by Matias222** [comment] 2023-08-01 00:33
I still have the issue, when trying this ans=supabase_client.rpc("count_duplicate_emails",{}) I get <postgrest._sync.request_builder.SyncFilterRequestBuilder object at 0x10fe32ee0> and when trying ans=await supabase_client.rpc("count_duplicate_emails", {}).execute() it returns AttributeError: 'int' object has no attribute 'get', it works when calling with a Post request, but not with the Supabase python library

**Comment by ShantanuNair** [comment] 2023-09-01 16:10
Same issue as OP. Version 1.0.4

**Comment by ShantanuNair** [comment] 2023-09-01 16:16
@0xDeadcell This did nothing for me.

**Comment by ShantanuNair** [comment] 2023-09-04 10:39
Hey @kiwicopple, looks like RPC functionality is largely broken for supabase python, since we cannot use RPC calls which return values

**Comment by silentworks** [comment] 2023-09-04 10:49
@ShantanuNair we have seen this issue and are currently looking into it.

**Comment by J0** [comment] 2023-09-08 17:54
Hey,

Wanted to echo the sentiment above ^ we'll push out a fix shortly

**Comment by silentworks** [comment] 2023-09-17 20:46
A PR has been opened to fix this issue and we will get it merged in soon https://github.com/supabase-community/postgrest-py/pull/309

**Comment by silentworks** [comment] 2023-09-29 13:05
This should now be available in the latest v1.1.0 of the `supabase-py` library.

**Closed** 2023-10-02 02:13 UTC

**Comment by Joonel** [comment] 2023-11-13 22:13
The issue is present again in v2.0.3.

**Comment by silentworks** [comment] 2023-11-14 11:45
@Joonel we haven't changed much in the underlying `postgrest-py` library since the v1.1.0 release of the `supabase-py` library. Please provide a reproducible example repo of the issue persisting and we'll take a look into it.

**Comment by Joonel** [comment] 2023-11-24 12:59
@silentworks here is a reproducible example repo https://github.com/Joonel/rpc-issue
