### ISSUE TITLE
cannot authenticate user 

### ISSUE THREAD

**Issue by shawnesquivel** [supabase-community/supabase-py#645] opened 2023-12-17 23:41 UTC
**Describe the bug**
Even after verifying the user is authenticated, I cannot access my data.

I've confirmed through print statements that
- My user is authenticated as it generates me the access token
- The SQL is valid (works when I turn off RLS or if I provide the `access_token` to the cURL request)

I created two simple RLS policies for allowing
- inserts for authenticated users
- selects for authenticated users

```

CREATE POLICY "Enable insert for authenticated users only" ON "public"."todos"
AS PERMISSIVE FOR INSERT
TO authenticated

WITH CHECK (true)

```
**To Reproduce**
1. Create a table called todos with these columns 
<img width="751" alt="image" src="https://github.com/supabase-community/supabase-py/assets/94336773/c256d1b4-9852-4592-9eda-9347e950026f">

2. Create a RLS for insert
```
CREATE POLICY "Enable insert for authenticated users only" ON "public"."todos"
AS PERMISSIVE FOR INSERT
TO authenticated

WITH CHECK (true)

```
3. Use this code snippet as mentioned in #185 

```
    user = supabase.auth.sign_in_with_password({"email": email, "password": password})
    session = supabase.auth.get_session()  # this refreshes the access token if needed
    # tried this first
    supabase.postgrest.auth(
        # verified that this was real
        token=session.access_token
    )  # this sets the right "authorization" header on HTTP requests to PostgREST
    res = supabase.auth.set_session(session.access_token, session.refresh_token)
    select_data = supabase.table("todos").select("*").execute()
    print(select_data)
    insert_data = supabase.table("todos").insert({"name": "Buy milk"}).execute()
    print(insert_data)

```

Results:
Data is empty 
```
data=[] count=None
```

RLS error for insert:
```
    insert_data = supabase.table("todos").insert({"name": "Buy milk"}).execute()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 70, in execute
    raise APIError(r.json())
postgrest.exceptions.APIError: {'code': '42501', 'details': None, 'hint': None, 'message': 'new row violates row-level security policy for table "todos"'}

```

**Expected behavior**
As tested with RLS off, I can retrieve the contents of the rows. 
I can also view do a cURL request with the access_token of the session and retrieve the rows.
So my best guess is that although the user itself is successfully authenticated, there's no way for us to successfully tell the **client** which executes the queries, that we have given it an authenticated user, even though I have used the workarounds mentioned by the community.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 14.1.2 
 - Version: 2.3.0

**Comment by Atticuszz** [comment] 2023-12-18 01:36
hi，u can try skip 
# tried this first
    supabase.postgrest.auth(
        # verified that this was real
        token=session.access_token
    )  # this sets the right "authorization" header on HTTP requests to PostgREST
，use the token from  authresponse by auth.sign in

**Comment by shawnesquivel** [comment] 2023-12-18 03:47
> hi，u can try skip
> 
> # tried this first
> ```
> supabase.postgrest.auth(
>     # verified that this was real
>     token=session.access_token
> )  # this sets the right "authorization" header on HTTP requests to PostgREST
> ```
> 
> ，use the token from authresponse by auth.sign in

Hi @Atticuszz  thanks for the reply, I'm not sure what you meant but I tried and it's not returning any data. 

```
    user = supabase.auth.sign_in_with_password({"email": email, "password": password})

 res = supabase.auth.set_session(
        user.session.access_token, user.session.refresh_token
    )
    print(f"access token {user.session.access_token}")



```


Prints the following:

```
access token eyJhb.....

2023-12-17 19:45:08,570:INFO - HTTP Request: GET https://qctnbkfmquxoifgzwmml.supabase.co/rest/v1/todos?select=%2A "HTTP/1.1 200 OK"

data=[] count=None
```

**Comment by silentworks** [comment] 2023-12-20 14:51
I'm a bit confused as to why you are passing around the `access_token` when it's handled for you automatically. Can you create a minimal reproducible example repository with the trouble code in it. I have a notes project here which is doing what you mentioned here without any issues https://github.com/silentworks/flask-notes.

**Comment by NajibPro** [comment] 2023-12-25 17:27
i have the same problem as you, and still didn't find the solution for it

**Comment by esousacosta** [comment] 2023-12-29 11:17
Hello, I'm facing the same issue, but I'm not sure if I'm using the correct functions at the correct place.

Here's an example:
```ptyhon
from supabase import create_client, Client
from supabase.lib.client_options import ClientOptions

supabaseUrl = 'https://yutoqmiqyxotuwifignh.supabase.co'
# This is the anon key
supabaseKey = 'myAnonKey'
supabase: Client = create_client(supabaseUrl, supabaseKey)

# I was using this var to print only, and it shows all of the connection data, as expected
signInData = supabase.auth.sign_in_with_password({"email": "email@gmail.com", "password": "my-password"})

# Here I get the same row violation error as the author of the post
data, count = supabase.table("books_history").insert({"isbn": "8888", "dates": [], "prices": []}).execute()
```

At the _insert_ call, I get the following error:
postgrest.exceptions.APIError: {'code': '42501', 'details': None, 'hint': None, 'message': 'new row violates row-level security policy for table "books_history"'}

In addition, I also tried configuring the headers to send the request using the "Authorization: Bearer access_token" information, but I couldn't figure out how to do it properly. If I inject the POST request using the RESTED chrome extension, it works perfectly, though.
![image](https://github.com/supabase-community/supabase-py/assets/17733172/cdccf77f-622c-4049-81c3-c5e7fcd2f793)

Does anyone have an idea of what I'm missing here? Or is it an issue?

Thank you in advance!

**Comment by silentworks** [comment] 2023-12-29 20:52
Folks I have provided an example repo above doing what you are asking here and no one with the issue seems to be providing an example repo with the issue. It is really hard to fix something you cannot replicate or even give correct help. Please provide an minimal example repository with this issue present.

**Comment by adriantil** [comment] 2024-01-05 18:15
I'm having the same issue and came to this through Google.  @silentworks I can understand the frustration with not getting a repo, but the issue doesn't need a full repository worth of code.  Reproducing it can be done by creating a table in supabase, turning on RLS for only authenticated users, and then trying an insert or select using the Python supabase import.  Token authentication is NOT being handled automatically, that is the issue here:

```
data = supabase.auth.sign_in_with_password({
     ...
})
data, count = supabase.table("tasks").insert({
     ...
}).execute
```
Sanitized output:
```
2024-01-05 12:55:59,371:INFO - HTTP Request: POST <URL>/auth/v1/token?grant_type=password "HTTP/1.1 200 OK"
2024-01-05 12:55:59,513:INFO - HTTP Request: POST <URL>rest/v1/tasks "HTTP/1.1 403 Forbidden"
Traceback (most recent call last):
  File "<PATH>/postgres-test.py", line 311, in <module>
    }).execute()
       ^^^^^^^^^
  File "<venv path>/lib/python3.12/site-packages/postgrest/_sync/request_builder.py", line 70, in execute
    raise APIError(r.json())
postgrest.exceptions.APIError: {'code': '42501', 'details': None, 'hint': None, 'message': 'new row violates row-level security policy for table "tasks"'}
```
I'm not trying to be an a-hole here, but providing an example flask app and telling people to look through it isn't particularly helpful.  If there is a step I'm missing in between sign-in and interacting with the db I'd super appreciate some direction.  I've read the docs and think I'm doing things as indicated but could totally be missing something.  Happy to help debug as well.

**Comment by adriantil** [comment] 2024-01-05 18:40
For additional information:

Using postman I can hit the same endpoints: signing in with auth and then doing a select through a GET rather than a POST.

With RLS on that table set to any "authenticated" user I am not able to query the table and receive results using the python package.  I AM able to login with postman through the auth endpoint, get the access token, place that in the headers of a new call to the same table (with "bearer <access token" format") and receive the expected information.

So actions using python after a sign in aren't working, but a curl/requests/postman API request does.  Did I miss a step between logging in with email and password and trying to execute a query/insert?

**Comment by adriantil** [comment] 2024-01-05 18:54
Okay, here we go:

Does not work, returns no data.
```
supabase: Client = create_client(POSTGRES_URL, POSTGRES_PUBLIC_KEY)
data = supabase.auth.sign_in_with_password(
  {....}
)
# supabase.postgrest.auth(data.session.access_token)

data, count = supabase.table("tasks").select("*").execute()
print(data) # NO DATA, EMPTY LIST
supabase.auth.sign_out()
```
Manually setting the access token works, unknown about refresh token but that should probably be checked.
```
supabase: Client = create_client(POSTGRES_URL, POSTGRES_PUBLIC_KEY)
data = supabase.auth.sign_in_with_password(
  {....}
)
supabase.postgrest.auth(data.session.access_token)

data, count = supabase.table("tasks").select("*").execute()
print(data) #WORKS, FINDS EXPECTED RESULTS
supabase.auth.sign_out()
```

**Comment by brianft** [comment] 2024-01-06 06:05
@adriantil I'm running into the same issue you are having, but with inserting a row. Manually setting the access token the way you did not work. I've checked that I'm logged in and I have a valid access_token, and if I disable RLS, I'm able to perform an insert. Is there something else that needs to be done for Inserts?

```
data = supabase.auth.sign_in_with_password({"email": "xxxxx", "password": "xxxxx"})

supabase.postgrest.auth(data.session.access_token)

@app.post("/items/")
async def create_item(item: Item):
    item_data = item.model_dump()
    print(item_data)

data, count = supabase.table('uploads')\
          .insert(item_data)\
          .execute()
```

**Comment by Atticuszz** [comment] 2024-01-07 09:51
+1

**Comment by Atticuszz** [comment] 2024-01-07 10:53
> I'm a bit confused as to why you are passing around the `access_token` when it's handled for you automatically. Can you create a minimal reproducible example repository with the trouble code in it. I have a notes project here which is doing what you mentioned here without any issues https://github.com/silentworks/flask-notes.

thanks for sharing!  In the flask example, still have confusions 
on how it can recognize who send the request?

**Comment by silentworks** [comment] 2024-01-11 11:42
This should be address when PR #660 gets merged in.

**Comment by silentworks** [comment] 2024-01-11 11:46
> > I'm a bit confused as to why you are passing around the `access_token` when it's handled for you automatically. Can you create a minimal reproducible example repository with the trouble code in it. I have a notes project here which is doing what you mentioned here without any issues https://github.com/silentworks/flask-notes.
> 
> thanks for sharing! In the flask example, still have confusions on how it can recognize who send the request?

@Atticuszz magic. I'm joking, it works this way in Flask because each request creates and destroys a new client, so when a new client is called it checks the session if there is a access token saved and if it finds one it uses that for the Authorization header for the new client.

**Comment by Atticuszz** [comment] 2024-01-11 13:09
> > > I'm a bit confused as to why you are passing around the `access_token` when it's handled for you automatically. Can you create a minimal reproducible example repository with the trouble code in it. I have a notes project here which is doing what you mentioned here without any issues https://github.com/silentworks/flask-notes.
> > 
> > thanks for sharing! In the flask example, still have confusions on how it can recognize who send the request?
> 
> @Atticuszz magic. I'm joking, it works this way in Flask because each request creates and destroys a new client, so when a new client is called it checks the session if there is a access token saved and if it finds one it uses that for the Authorization header for the new client.
> 

hahaha，thanks ！got it

**Comment by shawnesquivel** [comment] 2024-01-11 14:47
> This should be address when PR #660 gets merged in. I just need to run a few more tests with this setup first before merging it in.

Awesome! Looking forward to it.

**Comment by silentworks** [comment] 2024-01-11 15:27
I've released version 2.3.3 which should address this issue, please report back if it has been fixed for you.

**Comment by snags141** [comment] 2024-01-17 10:51
> I've released version 2.3.3 which should address this issue, please report back if it has been fixed for you.

Thank you! Spent an hour tearing my hair out over this issue going back and forth with the docs before I came across this thread - Updated to 2.3.4 and now it's working as expected

**Comment by KateChern** [comment] 2024-01-18 14:10
> This should be address when PR #660 gets merged in. I just need to run a few more tests with this setup first before merging it in.

I'm glad I found this discussion here and that @silentworks addressed the issue for Flask applications. 
I am facing the exact same problem with FastAPI. Hope it will be resolved in the future too!

**Comment by Atticuszz** [comment] 2024-01-18 16:05
> > This should be address when PR #660 gets merged in. I just need to run a few more tests with this setup first before merging it in.
> 
> I'm glad I found this discussion here and that @silentworks addressed the issue for Flask applications. 
> I am facing the exact same problem with FastAPI. Hope it will be resolved in the future too! 

here's also a [template](https://github.com/Atticuszz/fastapi_supabase_template) for fastapi supabase，hope u enjoy it as well！😉

**Comment by KateChern** [comment] 2024-01-19 11:07
@Atticuszz that's great, thank you so much!

**Comment by adriantil** [comment] 2024-01-19 20:44
> I've released version 2.3.3 which should address this issue, please report back if it has been fixed for you.

Fixed!  Thank you for looking into it and pushing a fix so quickly!

**Comment by iamstarcode** [comment] 2024-01-21 16:11
Hi everybody, so if i get it right, we have to manually set access_token on both 
`supabase.auth.set_session(access_token, refresh_token="")` and `supabase.postgrest.auth(access_token)` 
the first will ensure we have a session, the second will ensure our **RLS** policies are hit when making SQL queries?

**Comment by eformx** [comment] 2024-01-22 02:40
@iamstarcode I couldn't get it to work as well.  All you need to do is use the Service Key for all crud operations or create a  Policy from the Dashboard to run the Select statement to access a table.

Hope this helps everyone trying to get the login to work. THIS should be in the docs!

```
from supabase import create_client
API_URL = 'https://blahblah'
API_KEY = 'blahblah'
All_Access_Key = 'blahblahServiceKey'
supabase = create_client(API_URL, All_Access_Key)

# delete a row
supabase.table("your_table_name").delete().eq("id", 1).execute()

data, count = supabase.table("your_table_name").select("*").execute()
print(data) #WORKS, FINDS EXPECTED RESULTS
```

**Comment by iamstarcode** [comment] 2024-01-22 07:30
Hi @eformx , I got it to work by passing the access_token to the `supabase.postgrest.auth(access_token)`, all the policy also works correctly now, and I think Supabase discourages using service key to make CRUD operations for users, it should only be for Admin use cases

**Comment by snags141** [comment] 2024-01-22 08:06
It should work without the service 'superuser' key as long as you first log in with the email and password of a Supabase user that meets the RLS policy as in the OP

E.g: to update the example given by eformx above
```
from supabase import create_client
API_URL = 'https://blahblah'
API_KEY = 'blahblah'
SUPABASE_ANON_KEY = 'blahblahAnonKey'
supabase = create_client(API_URL, SUPABASE_ANON_KEY)

--- this part here ---
# Log in with your supabase email and password
my_session = supabase.auth.sign_in_with_password({"email": "my-supabase-serviceaccount@email.com", "password": "some-secure-password"})
--- this part here ---

# delete a row
supabase.table("your_table_name").delete().eq("id", 1).execute()

data, count = supabase.table("your_table_name").select("*").execute()
print(data)
```

You can then fetch the users access and refresh token from `my_session` as needed. It's a bit of a pain to manage when you're implementing this on a backend server somewhere but I prefer this approach over using the service key. Least privilege yada yada.

After the 2.3.3 update this works great for me, but the service key works too.

**Comment by iamstarcode** [comment] 2024-01-22 08:34
@snags141 my use case is a little different, at the backend, I am not doing authentication, I am only doing authentication from a frontend(Nextjs). I then pass the access_token to the backend, that's why I am setting the session using the access_token

**Comment by eformx** [comment] 2024-01-22 14:20
@snags141 that works great, but until I created a policy it did not work.  Once I created a policy that worked. They need to update the docs (Step 1.  Create a policy...).  

Do you know how I can resuse that connection with the python vecs module.  In the docs it says to connect with a url with the username and password which works, but is it possible to pass in the session somehow?

```
Import vecs
DB_CONNECTION = "postgres://<user>:<password>@<host>:<port>/<db_name>"
vx = vecs.create_client(DB_CONNECTION) **# how to pass credentials here?**
docs = my_session.get_or_create_collection(name="docs", dimension=3)
```

**Comment by nyck33** [comment] 2024-02-19 05:56
```
# get supabase env vars and make client
url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

print(url, key)
supabase: Client = create_client(url, key)

def insert_dataframe_to_supabase(df, embeddings, source, source_id, document_id, author, url):
    for index, row in df.iterrows():
        embedding = embeddings[index]
        data = {
            "source": source,
            "source_id": source_id,
            "content": row['segmented_text'],
            "document_id": document_id,
            "author": author,
            "url": url,
            "embedding": embedding
        }
        supabase.table("korean").insert(data).execute()

dfs = [vocab2_df] #, grammar1_df, grammar2_df]
all_args = [vocab2_args] #, grammar1_args, grammar2_args]
# %%
# iterate over dfs and all_args to call insert_dataframe_to_supabase
for df, args in zip(dfs, all_args):
    insert_dataframe_to_supabase(df, df['embedding'], **args)
```
I get 201 Created but then it gives me URL to click and it says no API key and the insertions don't occur.  

```
supabase-2.3.5

**Comment by nyck33** [comment] 2024-02-19 05:59
![image](https://github.com/supabase-community/supabase-py/assets/25189545/4ada7948-178a-4816-8ec1-fd351c98a903)

but click that and get

```
{"message":"No API key found in request","hint":"No `apikey` request header or url param was found."}
```
on the free tier is there limit to number of operations?

**Comment by nyck33** [comment] 2024-02-19 06:06
@snags141 what if I signed up and logged in with my github account?  do I even have a password to use for 
```
--- this part here ---
# Log in with your supabase email and password
my_session = supabase.auth.sign_in_with_password({"email": "my-supabase-serviceaccount@email.com", "password": "some-secure-password"})
--- this part here ---
```

**Comment by nyck33** [comment] 2024-02-19 06:14
but `response = supabase.table("korean").select("*").execute()
` works.  Only insert returns that no api key error?

**Comment by snags141** [comment] 2024-02-19 07:02
@nyck33 you'd probably have to use the OAuth python call since there's no password to sign in with

[https://supabase.com/docs/reference/python/auth-signinwithoauth](https://supabase.com/docs/reference/python/auth-signinwithoauth)

I've never used it myself so wouldn't be able to help much there. I presume it's an interactive only log in though so would fire up a browser and prompt you to log in with github when you use it. So you wouldn't be able to use this in a headless environment (ie on a Linux server with no desktop environment) but I could be wrong. The docs are pretty light

On the second point, i would take a guess that Supabase is allowing you to select anonymously (using anon key only) but requires auth for insert and other write actions hence why selects work without being logged in

Per the docs, the anon key has very few privileges but you can allow insert and other actions with an RLS policy - best practice however is to use an authenticated user for everything

[https://supabase.com/docs/guides/api/api-keys](https://supabase.com/docs/guides/api/api-keys)

**Comment by nyck33** [comment] 2024-02-19 07:49
So once I create an account with GitHub, sign in with it there is no way besides the Oauth non-programmatic way to login?  That seems kind of dumb.  This platform is for developers no?

**Comment by nyck33** [comment] 2024-02-19 09:34
@snags141 I'm not `os.environ.get()` for my anon key although it's in my .env only the secret key so based on that I am guessing the secret key can also work as an anon key for the `select` statement.

**Comment by nyck33** [comment] 2024-02-19 09:36
Also noticed your web UI does not work very well, I had to click Browse to get my .csv although it claims that I can drag and drop files there and it looks like it's one at a time as well.

**Comment by nyck33** [comment] 2024-02-19 10:07
under Authentication on the Web UI there is a way to add users though so will try that.

**Comment by nyck33** [comment] 2024-02-19 10:35
```#%%
from supabase import create_client, Client
url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

print(url, key)
supabase: Client = create_client(url, key)

#%%
import os
SUPABASE_EMAIL = os.environ.get("SUPABASE_EMAIL")
SUPABASE_PASSWORD = os.environ.get("SUPABASE_PASSWORD")

# print secrets
print(SUPABASE_EMAIL, SUPABASE_PASSWORD)
#%%
my_session = supabase.auth.sign_in_with_password({"email": SUPABASE_EMAIL, "password":SUPABASE_PASSWORD})
'''
data = supabase.auth.sign_in_with_oauth({
  "provider": 'github'
})
'''
#%%

data = supabase.auth.get_user()
#%%
print(data)
# %%
def insert_dataframe_to_supabase(df,source, source_id, document_id, author, url):
    for index, row in df.iterrows():
        embedding = row['embedding']
        data = {
            "source": source,
            "source_id": source_id,
            "content": row['content'],
            "document_id": document_id,
            "author": author,
            "url": url,
            "embedding": embedding
        }
        data, count = supabase.table("korean").insert(data).execute()
        if len(data) > 0:
            print(f"Inserted {len(data)} rows into the korean table.")  
        else:
            print(f"Failed to insert rows into the korean table.")
            break
.
.
. # some code left out here 
dfs = [vocab1_df, vocab2_df, grammar1_df, grammar2_df]
all_args = [vocab1_args, vocab1_df, grammar1_args, grammar2_args]
# %%
# iterate over dfs and all_args to call insert_dataframe_to_supabase

for df, args in zip(dfs, all_args):
    insert_dataframe_to_supabase(df, **args)
```

gets me the same result

![image](https://github.com/supabase-community/supabase-py/assets/25189545/a81a7a7c-dcb3-4178-a7c6-189c75ee0a42)

that link when clicked: 
```
{"message":"No API key found in request","hint":"No `apikey` request header or url param was found."}
```
I tried every way to get data on my table, .csv manually on web UI, this way, only thing left is I guess vecs  api here:  https://supabase.com/docs/guides/ai/python/api

**Comment by nyck33** [comment] 2024-02-19 10:52
![image](https://github.com/supabase-community/supabase-py/assets/25189545/a5f87096-ce2d-49ae-8db2-31a90500c390)

It looks like the spinner is stuttering and that output does not show 1 row being inserted although I'm going 1 at a time:
```
def insert_dataframe_to_supabase(df,source, source_id, document_id, author, url):
    for index, row in df.iterrows():
        embedding = row['embedding']
        data = {
            "source": source,
            "source_id": source_id,
            "content": row['content'],
            "document_id": document_id,
            "author": author,
            "url": url,
            "embedding": embedding
        }
        data, count = supabase.table("korean").insert(data).execute()
        if len(data) > 0:
            print(f"Inserted {len(data)} rows into the korean table.")  
        else:
            print(f"Failed to insert rows into the korean table.")
            break
```
called like 
```
for df, args in zip(dfs, all_args):
    insert_dataframe_to_supabase(df, **args)
```

**Comment by nyck33** [comment] 2024-02-19 11:23
Thanks got it working, added another user on the web ui under Authentication and also uploaded .csv's on the web UI.

**Comment by silentworks** [comment] 2024-02-21 17:31
I think the original issue that was opened here has been resolved and there are too many unrelated comments being added to this issue. I'm closing this out as the original issue has been fixed. Open a new issue in relation to any new error you are getting.

**Closed by silentworks** 2024-02-21 17:31 UTC
Labels: bug
